[2024-11-08T18:30:31.796+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T18:30:31.812+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: backup_files_dag.backup_files manual__2024-11-08T15:30:29.406064+00:00 [queued]>
[2024-11-08T18:30:31.823+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: backup_files_dag.backup_files manual__2024-11-08T15:30:29.406064+00:00 [queued]>
[2024-11-08T18:30:31.824+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-08T18:30:31.839+0300] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): backup_files> on 2024-11-08 15:30:29.406064+00:00
[2024-11-08T18:30:31.847+0300] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-08T18:30:31.850+0300] {standard_task_runner.py:72} INFO - Started process 97 to run task
[2024-11-08T18:30:31.850+0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'backup_files_dag', 'backup_files', 'manual__2024-11-08T15:30:29.406064+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/backup_files_dag.py', '--cfg-path', '/tmp/tmp9uqc0ies']
[2024-11-08T18:30:31.852+0300] {standard_task_runner.py:105} INFO - Job 228: Subtask backup_files
[2024-11-08T18:30:31.909+0300] {task_command.py:467} INFO - Running <TaskInstance: backup_files_dag.backup_files manual__2024-11-08T15:30:29.406064+00:00 [running]> on host 1168f67a661e
[2024-11-08T18:30:32.003+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='backup_files_dag' AIRFLOW_CTX_TASK_ID='backup_files' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T15:30:29.406064+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-08T15:30:29.406064+00:00'
[2024-11-08T18:30:32.005+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-08T18:30:32.006+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-08T18:30:32.006+0300] {logging_mixin.py:190} INFO - Current task name:backup_files state:running start_date:2024-11-08 15:30:31.814272+00:00
[2024-11-08T18:30:32.007+0300] {logging_mixin.py:190} INFO - Dag name:backup_files_dag and current dag run status:running
[2024-11-08T18:30:32.008+0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T18:30:32.009+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-08T18:30:32.011+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cp -r /opt/***/source* /opt/***/backup']
[2024-11-08T18:30:32.023+0300] {subprocess.py:86} INFO - Output:
[2024-11-08T18:30:36.893+0300] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-08T18:30:36.920+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T18:30:36.921+0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=backup_files_dag, task_id=backup_files, run_id=manual__2024-11-08T15:30:29.406064+00:00, execution_date=20241108T153029, start_date=20241108T153031, end_date=20241108T153036
[2024-11-08T18:30:36.934+0300] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-08T18:30:36.936+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-08T18:30:36.942+0300] {logging_mixin.py:190} INFO - Dag name:backup_files_dag queued_at:2024-11-08 15:30:29.433750+00:00
[2024-11-08T18:30:36.943+0300] {logging_mixin.py:190} INFO - Task hostname:1168f67a661e operator:BashOperator
[2024-11-08T18:30:36.995+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-08T18:30:37.027+0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T18:30:37.035+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
