[2024-11-08T18:11:25.311+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T18:11:25.357+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_rate_dag.send_currency_rate scheduled__2024-11-08T00:00:00+00:00 [queued]>
[2024-11-08T18:11:25.384+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_rate_dag.send_currency_rate scheduled__2024-11-08T00:00:00+00:00 [queued]>
[2024-11-08T18:11:25.390+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-08T18:11:25.421+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): send_currency_rate> on 2024-11-08 00:00:00+00:00
[2024-11-08T18:11:25.444+0300] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-08T18:11:25.448+0300] {standard_task_runner.py:72} INFO - Started process 98 to run task
[2024-11-08T18:11:25.447+0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'currency_rate_dag', 'send_currency_rate', 'scheduled__2024-11-08T00:00:00+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/telegram-dag.py', '--cfg-path', '/tmp/tmpz_rv3_37']
[2024-11-08T18:11:25.461+0300] {standard_task_runner.py:105} INFO - Job 205: Subtask send_currency_rate
[2024-11-08T18:11:25.829+0300] {task_command.py:467} INFO - Running <TaskInstance: currency_rate_dag.send_currency_rate scheduled__2024-11-08T00:00:00+00:00 [running]> on host 1168f67a661e
[2024-11-08T18:11:26.538+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_rate_dag' AIRFLOW_CTX_TASK_ID='send_currency_rate' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-08T00:00:00+00:00'
[2024-11-08T18:11:26.546+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-08T18:11:26.547+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-08T18:11:26.548+0300] {logging_mixin.py:190} INFO - Current task name:send_currency_rate state:running start_date:2024-11-08 15:11:25.368452+00:00
[2024-11-08T18:11:26.551+0300] {logging_mixin.py:190} INFO - Dag name:currency_rate_dag and current dag run status:running
[2024-11-08T18:11:26.552+0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T18:11:28.140+0300] {python.py:240} INFO - Done. Returned value was: None
[2024-11-08T18:11:28.162+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T18:11:28.163+0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=currency_rate_dag, task_id=send_currency_rate, run_id=scheduled__2024-11-08T00:00:00+00:00, execution_date=20241108T000000, start_date=20241108T151125, end_date=20241108T151128
[2024-11-08T18:11:28.165+0300] {taskinstance.py:1563} INFO - Executing callback at index 0: task_success_callback
[2024-11-08T18:11:28.170+0300] {baseoperator.py:405} WARNING - TelegramOperator.execute cannot be called outside TaskInstance!
[2024-11-08T18:11:28.183+0300] {base.py:84} INFO - Retrieving connection 'telegram_notifier'
[2024-11-08T18:11:28.703+0300] {_client.py:1773} INFO - HTTP Request: POST https://api.telegram.org/bot7997662746:AAF5-dAcYJmpsa1Pe5cqSENUoRV5D2lj5NA/sendMessage "HTTP/1.1 200 OK"
[2024-11-08T18:11:28.755+0300] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-08T18:11:28.756+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-08T18:11:28.758+0300] {logging_mixin.py:190} INFO - Dag name:currency_rate_dag queued_at:2024-11-08 15:11:19.328906+00:00
[2024-11-08T18:11:28.760+0300] {logging_mixin.py:190} INFO - Task hostname:1168f67a661e operator:PythonOperator
[2024-11-08T18:11:28.787+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-08T18:11:28.832+0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T18:11:28.837+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
